project:
  name: cloudformation-lab2-group8
  regions:
  - us-east-1
  package-lambda: false
  parameters:
    KeyName: 'terraform-lab'

tests:
  infrastructure:
    template: cloudformation.yml
    regions:
    - us-east-1
    parameters:
      Prefix: test-infrastructure
      VpcCidr: 10.0.0.0/16
      PublicSubnetCidr: 10.0.1.0/24
      PrivateSubnetCidr: 10.0.2.0/24
      AllowedIp: 0.0.0.0/0
      InstanceType: t2.micro
